### ISSUE TITLE
gloo error  

### ISSUE THREAD

**Issue by JamesKasperYu** [mapillary/inplace_abn#89] opened 2019-02-17 06:57 UTC
Hi,
      I used distributed train with 'gloo' method but got error:
```       
File "/home/yuxb/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yuxb/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/yuxb/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/home/yuxb/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupGloo object at 0x7fdf2daaadc0>, [[tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0..
```
Thanks for your help.

**Comment by JamesKasperYu** [comment] 2019-02-17 08:08
nccl got zhe same error

**Comment by rotabulo** [comment] 2019-02-17 12:10
@JamesKasperYu do you get the error by running which script?

**Comment by JamesKasperYu** [comment] 2019-02-17 12:50
I just runed my net by replace bn+relu as inplace_abn.Before replaced bn+relu,it worked well.And the net works well in inplace_abn version with pytorch0.4.1.

**Comment by JamesKasperYu** [comment] 2019-02-17 12:55
Before replace bn+relu,the type of process_group is torch.distributed.ProcessGroupGloo,bucket_size is 4.
After that,the type of process_group is also torch.distributed.ProcessGroupGloo,bucket_size is 6.

**Comment by rotabulo** [comment] 2019-02-18 08:26
@JamesKasperYu are you using the synchronized version of inplace_abn ?

**Comment by JamesKasperYu** [comment] 2019-02-18 08:32
yes,and it seem that the no sync version get the same error.

**Comment by rotabulo** [comment] 2019-02-18 08:35
@JamesKasperYu does it work with bn+relu with PyTorch v1.0? Your issue could be related to https://github.com/pytorch/pytorch/issues/13273 ?

**Comment by JamesKasperYu** [comment] 2019-02-18 08:38
yes,it works well with bn+relu with PyTorch v1.0.

**Comment by rotabulo** [comment] 2019-02-18 08:55
@JamesKasperYu we never encountered such issue, in particular with nccl. Can you provide us with some possibly small piece of code that reproduces the issue?

**Comment by JamesKasperYu** [comment] 2019-02-18 10:46
@rotabulo I make a mistake,it does not work with bn+relu with PyTorch v1.0,when I define a net in init like that:
```
        self.conv1 = nn.Conv2d(3, 16,kernel_size=7, stride=8, padding=3, bias=False)
        self.bn1 = BatchNorm(16)
        self.relu = nn.ReLU(inplace=True)
        self.classifier = nn.Conv2d(16, class_count, 1, bias=True)
```
it works well,but after add a conv under self.relu like that:
```
        self.conv1 = nn.Conv2d(3, 16,kernel_size=7, stride=8, padding=3, bias=False)
        self.bn1 = BatchNorm(16)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = nn.Conv2d(16, 16,1, bias=False)
        self.classifier = nn.Conv2d(16, class_count, 1, bias=True)
'''
it get the error.

**Comment by rotabulo** [comment] 2019-02-18 10:47
@JamesKasperYu can you share also the forward computation?

**Comment by JamesKasperYu** [comment] 2019-02-18 10:51
two nets use the same forward computation:
```
        x1 = self.conv1(x)
        x1 = self.bn1(x1)
        x1 = self.relu(x1)
        x = self.classifier(x1)
```

**Comment by rotabulo** [comment] 2019-02-18 10:54
@JamesKasperYu I suspect this is definitely related to pytorch/pytorch#13273. Apparently you cannot have unused parameters, which is the case when you add conv2. You could try to use the implementation of DistributedDataParallel from apex (see the issue for details). I am also closing the issue, since it is not related to our repository.

**Closed by rotabulo** 2019-02-18 10:54 UTC
